### ISSUE TITLE
Error: no plugin found for a rule: "apply-shorthand-properties"

### ISSUE THREAD

**Issue by EvgenyOrekhov** [coderaiser/putout#47]
I saw this in the changelog:

> - (putout) plugin-apply-shorthand-properties: remove from default install

After I upgraded Putout to v14, I ran `npm i @putout/plugin-apply-shorthand-properties`, but I'm still getting this error:

```text
eslint .

Oops! Something went wrong! :(

ESLint: 7.18.0

Error: no plugin found for a rule: "apply-shorthand-properties"
```

This is what I have in my `.eslintrc.json`:

```text
  "rules": {
    "putout/putout": [
      "error",
      {
        "rules": {
          "apply-shorthand-properties": "on"
        }
      }
    ]
  }
```

Did I do something wrong? How do I use `apply-shorthand-properties` with Putout v14 via ESLint?

**Comment by coderaiser** [comment]
You should add `plugins` section, so `putout` can load this `plugin` result config will look this way:

```json
{
"rules": {
    "putout/putout": [
      "error",
      {
        "rules": {
          "apply-shorthand-properties": "on"
        },
        "plugins": [
          "apply-shorthand-properties"
       ]
      }
    ]
  }
}
```

Is it works for you?

**Comment by EvgenyOrekhov** [comment]
Thanks, that fixes the ESLint CLI. But VS Code linting still doesn't work. I'm getting this in VS Code log:

```text
[Info  - 2:41:11 PM] ESLint server is starting
[Info  - 2:41:12 PM] ESLint server running in node v12.14.1
[Info  - 2:41:12 PM] ESLint server is running.
[Info  - 2:41:16 PM] ESLint library loaded from: C:\eslint-config-hardcore\node_modules\eslint\lib\api.js
[Info  - 2:41:21 PM] Failed to load plugin 'putout' declared in '.eslintrc.json » ./index.json » ./base.json': Cannot find module 'putout/parse-options' Require stack: - C:\eslint-config-hardcore\node_modules\eslint-plugin-putout\lib\putout\index.js - C:\eslint-config-hardcore\node_modules\eslint-plugin-putout\lib\index.js - C:\eslint-config-hardcore\node_modules\@eslint\eslintrc\lib\config-array-factory.js - C:\eslint-config-hardcore\node_modules\@eslint\eslintrc\lib\index.js - C:\eslint-config-hardcore\node_modules\eslint\lib\cli-engine\cli-engine.js - C:\eslint-config-hardcore\node_modules\eslint\lib\cli-engine\index.js - C:\eslint-config-hardcore\node_modules\eslint\lib\api.js - c:\Users\user\.vscode\extensions\dbaeumer.vscode-eslint-2.1.14\server\out\eslintServer.js
```

**Comment by coderaiser** [comment]
The reason is `node v12`, `putout` droped support of it a couple versions ago. Consider upgrading to [node v 14](https://nodejs.org/en/), it is `LTS`.

**Comment by EvgenyOrekhov** [comment]
VS Code comes **bundled** with Node v12, it can't be upgraded.

**Comment by EvgenyOrekhov** [comment]
![image](https://user-images.githubusercontent.com/8045060/106150731-aebefd00-618c-11eb-9e6a-0b1f27c6ebdb.png)

**Comment by EvgenyOrekhov** [comment]
I'll open a separate issue for VS Code problem.
